### PR TITLE
#162170667 setup coveralls

### PR DESCRIPTION
**Pull request by okoroemeka**
#### What does this PR do?
Have setup for coveralls

#### Description of Task to be completed?
Have coveralls working on Author's Haven App

#### How should this be manually tested?
N/A

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#162170667 ](https://www.pivotaltracker.com/story/show/162170667)

### CODE REVIEW

**Review by marcdomain — APPROVED** [review]
LGTM!

**Review by akhilome — APPROVED** [review]

**Comment by Johnsonojo** [comment]
Looks good to me.

**Review by oluwajuwon — APPROVED** [review]
LGTM!

**Review by frostyblok — APPROVED** [review]
Good job!

**Pull request merged**
